[metadata]
name = warehouse
version = attr: warehouse.version.__version__
description = Applications of Metaheuristic Optimization in Python.
long_description = file: README.md
long_description_content_type = text/markdown
keywords =
    bin packing
license = GPL 3.0
license_file = LICENSE
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Science/Research
    Natural Language :: English
    Natural Language :: German
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.14
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Topic :: Scientific/Engineering :: Mathematics
url = https://thomasweise.github.io/warehouse
author = Thomas Weise
author_email = tweise@ustc.edu.cn
maintainer = Thomas Weise
maintainer_email = tweise@ustc.edu.cn
project_urls =
    Documentation = https://thomasweise.github.io/warehouse
    Source = https://github.com/thomasWeise/warehouse
    Tracker = https://github.com/thomasWeise/warehouse/issues

[options]
include_package_data = True
install_requires =
    numba >= 0.66.0
    numpy >= 2.4.6
    pycommons >= 0.8.103
packages = find:
python_requires = >= 3.12
zip_safe = False

[options.package_data]
warehouse = py.typed

[options.packages.find]
exclude =
    .coverage*
    .github*
    .mypy_cache*
    .pytest_cache*
    .ruff_cache*
    dist*
    docs*
    examples*
    moptipy.egg-info*
    warehouse.egg-info*
    tests*
