"""The warehouse simulation."""

from heapq import heapify, heappop, heappush
from typing import Callable, Final, Generator, Iterable

from pycommons.types import type_error

from warehouse.instance.bin import Bin
from warehouse.instance.event import (
    EARLIEST_START,
    BinIn,
    BinOut,
    EndEvent,
    Event,
    OverstockIn,
    OverstockOut,
    StartEvent,
    WarehouseIn,
    WarehouseOut,
)
from warehouse.instance.scenario import Scenario


class Simulation:
    """A warehouse simulation."""

    def __init__(self, scenario: Scenario) -> None:
        """
        Create the simulation.

        :param scenario: the scenario to simulate
        """
        if not isinstance(scenario, Scenario):
            raise type_error(scenario, "scenarion", Scenario)

        #: the scenario we are simulating
        self.scenario: Final[Scenario] = scenario
        #: the time index
        self.time: int = EARLIEST_START

        #: the internal queue
        self.__queue: Final[list[Event]] = []
        #: the amount of over
        self.__overstock: Final[list[int]] = [0] * scenario.n_materials

        #: the eligible bins for a given material
        self.__empty_material_bins: Final[tuple[list[int], ...]] = tuple(
            [] for _ in range(scenario.n_materials))
        #: the empty random bins
        self.__empty_random_bins: Final[list[int]] = []
        #: the used bins for a given material
        self.__used_material_bins: Final[tuple[list[int], ...]] = tuple(
            [] for _ in range(scenario.n_materials))

        use_material = scenario.materials[0]
        use_bin = scenario.bins[0]
        #: the shared BinIn event
        self.__bin_in: Final[BinIn] = BinIn(
            EARLIEST_START, use_material, use_bin)
        #: the shared BinOut event
        self.__bin_out: Final[BinOut] = BinOut(
            EARLIEST_START, use_material, use_bin)
        #: the shared overstock in event
        self.__overstock_in: Final[OverstockIn] = OverstockIn(
            EARLIEST_START, use_material, 1)
        #: the shared overstock out event
        self.__overstock_out: Final[OverstockOut] = OverstockOut(
            EARLIEST_START, use_material, 1)
        #: the bins
        self.__bins: Final[tuple[Bin, ...]] = scenario.bins

    def __start(self) -> None:
        """Begin the simulation."""
        os: Final[list[int]] = self.__overstock
        emb: Final[tuple[list[int], ...]] = self.__empty_material_bins
        erb: Final[list[int]] = self.__empty_random_bins
        umb: Final[tuple[list[int], ...]] = self.__used_material_bins

        erb.clear()
        for i, eb in enumerate(emb):
            os[i] = 0
            eb.clear()
            umb[i].clear()

        for xbin in self.scenario.bins:
            mat = xbin.material
            if mat is None:
                erb.append(xbin.key)
            else:
                emb[mat.key].append(xbin.key)

        queue: Final[list[Event]] = self.__queue
        queue.clear()
        queue.extend(self.scenario.events)
        heapify(queue)

        self.time = EARLIEST_START

    def simulate(self) -> Generator[Event, None, None]:
        """
        Run the simulation.

        :return: the sequence of events.
        """
        self.__start()

        queue: Final[list[Event]] = self.__queue
        if list.__len__(queue) <= 0:
            yield StartEvent(self.time)
        elif queue[0].__class__ is not StartEvent:
            self.time = queue[0].time
            yield StartEvent(queue[0].time)

        router: Final = _EVENT_ROUTER
        quitter = _QUIT
        eid: int | None = None
        while queue:
            event: Event = heappop(queue)
            self.time = event.time
            yield event

            eid = id(event.__class__)
            if eid == quitter:
                break
            nested = router(eid)(self, event)
            if nested is not None:
                yield from nested

        queue.clear()

        if (eid is None) or (eid != quit):
            yield EndEvent(self.time)

    def enqueue(self, event: Event) -> None:
        """
        Add an event to the simulation's event queue.

        :param event: the event to add
        """
        heappush(self.__queue, event)

    def _ignore(self, _: Event) -> None:
        """
        Ignore this kind of event.

        :param _: the event
        """

    def _error(self, event: Event) -> None:
        """
        Handle an event that is not permitted.

        :param event: the event
        """
        raise ValueError(
            f"An event has occurred in the input event stream of a simulation"
            f" at time {self.time} that is not permitted: {event!r}. Such "
            f"events can only be generated by the simulation (as output) but "
            f"you cannot trigger them by yourself as input to the "
            f"simulation.")

    def _warehouse_in(self, event: WarehouseIn) -> Generator[
            Event, None, None]:
        """
        Store material into the warehouse.

        :param event: the event with the information about the material
            to be stored
        :return: the event stream
        """
        bin_in: Final[BinIn] = self.__bin_in
        object.__setattr__(bin_in, "time", self.time)
        object.__setattr__(bin_in, "material", event.material)

        material: Final[int] = event.material.key
        used_mat_bins: Final[list[int]] = self.__used_material_bins[material]
        empty_mat_bins: Final[list[int]] = self.__empty_material_bins[material]
        empty_random_bins: Final[list[int]] = self.__empty_random_bins
        bins: Final[tuple[Bin, ...]] = self.__bins
        amount: int = event.amount

        source: list[int] = empty_mat_bins
        while amount > 0:
            if not source:
                if source is empty_random_bins:
                    break
                source = empty_random_bins
                continue
            xbin = source.pop()
            object.__setattr__(bin_in, "where", bins[xbin])
            yield bin_in
            used_mat_bins.append(xbin)
            amount -= 1

        if amount > 0:
            overstock_in: Final[OverstockIn] = self.__overstock_in
            object.__setattr__(overstock_in, "time", self.time)
            object.__setattr__(overstock_in, "material", event.material)
            object.__setattr__(overstock_in, "amount", amount)
            yield overstock_in
            self.__overstock[material] += amount

    def _warehouse_out(self, event: WarehouseOut) -> Generator[
            Event, None, None]:
        """
        Remove material from the warehouse.

        :param event: the event
        """
        material: Final[int] = event.material.key
        amount: int = event.amount
        overstock: Final[list[int]] = self.__overstock

        overstocked = overstock[material]
        if overstocked > 0:
            reduction = min(overstocked, amount)
            amount -= reduction
            overstock[material] = overstocked - reduction
            overstock_out: Final[OverstockOut] = self.__overstock_out
            object.__setattr__(overstock_out, "time", self.time)
            object.__setattr__(overstock_out, "material", event.material)
            object.__setattr__(overstock_out, "amount", reduction)
            yield overstock_out

        if amount <= 0:
            return

        bins: Final[tuple[Bin, ...]] = self.__bins
        used_mat_bins: Final[list[int]] = self.__used_material_bins[material]
        empty_mat_bins: Final[list[int]] = \
            self.__empty_material_bins[material]
        empty_random_bins: Final[list[int]] = self.__empty_random_bins
        bin_out: Final[BinOut] = self.__bin_out
        object.__setattr__(bin_out, "time", self.time)
        object.__setattr__(bin_out, "material", event.material)

        # We will get an IndexError if you try to take out more material than
        # what is currently stored in the warehouse
        while amount > 0:
            xbin = used_mat_bins.pop()
            vbin = bins[xbin]
            if vbin.material is None:
                empty_random_bins.append(xbin)
            else:
                empty_mat_bins.append(xbin)
            object.__setattr__(bin_out, "where", vbin)
            yield bin_out
            amount -= 1


#: the end event
_QUIT: Final[int] = id(EndEvent)

#: the event router
_EVENT_ROUTER: Final[Callable[[int], Callable[[
    Simulation, Event], Iterable[Event] | None]]] = {
    _QUIT: Simulation._ignore,  # type: ignore
    id(StartEvent): Simulation._ignore,  # type: ignore
    id(Event): Simulation._error,  # type: ignore
    id(BinIn): Simulation._error,  # type: ignore
    id(BinOut): Simulation._error,  # type: ignore
    id(OverstockIn): Simulation._error,  # type: ignore
    id(OverstockOut): Simulation._error,  # type: ignore
    id(WarehouseIn): Simulation._warehouse_in,  # type: ignore
    id(WarehouseOut): Simulation._warehouse_out,  # type: ignore
}.__getitem__
